#!/bin/bash

function show_ping() {
    OUTPUT=$(sudo mtr -i 0.5 -z -j -n "$3")
    if [ $(echo "$OUTPUT" | jq -r '.report.hubs[-1]."Loss%"') == "100" ]; then
	AVG=$(echo "$OUTPUT" | jq -r '.report.hubs[-2].Avg')
	ASN=$(echo "$OUTPUT" | jq -r '.report.hubs[-2].ASN')
    else
	AVG=$(echo "$OUTPUT" | jq -r '.report.hubs[-1].Avg')
	ASN=$(echo "$OUTPUT" | jq -r '.report.hubs[-1].ASN')
    fi
    echo "$1	$2	$3	$AVG	$ASN"
}

for DN in $@
do
   show_ping "$DN" "direct " $(dig +short "$DN" | tail -n 1) &
   show_ping "$DN" "114    " $(dig +short "$DN" @114.114.114.114 | tail -n 1) &
   show_ping "$DN" "8888   " $(dig +short "$DN" @8.8.8.8 | tail -n 1) &
   show_ping "$DN" "gtls   " $(bin/doh -q --short --url "gtls" "$DN" | tail -n 1) &
   show_ping "$DN" "google " $(bin/doh -q --short --url "google" "$DN" | tail -n 1) &
   show_ping "$DN" "opendns" $(dig +short "$DN" @208.67.222.222 | tail -n 1) &
   show_ping "$DN" "one    " $(bin/doh -q --short --url "one" "$DN" | tail -n 1) &
   show_ping "$DN" "cf     " $(bin/doh -q --short --url "cf" "$DN" | tail -n 1) &
   show_ping "$DN" "quad9  " $(bin/doh -q --short --url "9tls" "$DN" | tail -n 1) &
   show_ping "$DN" "auguard" $(bin/doh -q --short --url "augtls" "$DN" | tail -n 1) &
   show_ping "$DN" "nextdns" $(bin/doh -q --short --url "nexttls" "$DN" | tail -n 1) &
   wait
done
